# Generated by Django 5.1.6 on 2025-02-24 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0003_remove_account_customer_account_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking_app.userprofile'),
        ),
    ]
